"""add_youtube_video_id_to_exercise

Revision ID: 5d1346d35deb
Revises: 3b06c0ce677e
Create Date: 2026-04-15 15:24:53.526340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5d1346d35deb'
down_revision: Union[str, None] = '3b06c0ce677e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('youtube_video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'youtube_video_id')
    # ### end Alembic commands ###
