from datetime import date

from sqlmodel import Session, select

from src.dispatch.exceptions import NotFoundError
from src.dispatch.exercise.models import Exercise
from src.dispatch.workout.models import (
    WorkoutPlan,
    WorkoutPlanDay,
    WorkoutPlanDayRead,
    WorkoutPlanExercise,
    WorkoutPlanExerciseRead,
    WorkoutPlanRead,
)


def get(*, db_session: Session, plan_id: int) -> WorkoutPlan | None:
    return db_session.get(WorkoutPlan, plan_id)


def get_all(*, db_session: Session, user_id: int) -> list[WorkoutPlan]:
    statement = select(WorkoutPlan).where(WorkoutPlan.user_id == user_id).order_by(WorkoutPlan.created_at.desc())
    return list(db_session.exec(statement).all())


def get_plan_read(*, db_session: Session, plan_id: int) -> WorkoutPlanRead | None:
    plan = get(db_session=db_session, plan_id=plan_id)
    if not plan:
        return None
    return _to_plan_read(db_session=db_session, plan=plan)


def get_today_plan(*, db_session: Session, user_id: int) -> WorkoutPlanDayRead | None:
    today = date.today()
    day_of_week = today.weekday()

    statement = (
        select(WorkoutPlan)
        .where(WorkoutPlan.user_id == user_id)
        .where(WorkoutPlan.valid_from <= today)
        .where(WorkoutPlan.valid_to >= today)
        .order_by(WorkoutPlan.created_at.desc())
    )
    plan = db_session.exec(statement).first()
    if not plan:
        return None

    day_stmt = (
        select(WorkoutPlanDay)
        .where(WorkoutPlanDay.plan_id == plan.id)
        .where(WorkoutPlanDay.day_of_week == day_of_week)
    )
    plan_day = db_session.exec(day_stmt).first()
    if not plan_day:
        return None

    return _to_day_read(db_session=db_session, day=plan_day)


def delete_active_plan(*, db_session: Session, user_id: int) -> None:
    """Delete all of the user's existing plans (one-plan-per-user invariant)."""
    plans = db_session.exec(
        select(WorkoutPlan).where(WorkoutPlan.user_id == user_id)
    ).all()
    for plan in plans:
        days = db_session.exec(
            select(WorkoutPlanDay).where(WorkoutPlanDay.plan_id == plan.id)
        ).all()
        for day in days:
            for ex in db_session.exec(
                select(WorkoutPlanExercise).where(WorkoutPlanExercise.plan_day_id == day.id)
            ).all():
                db_session.delete(ex)
            db_session.delete(day)
        db_session.delete(plan)
    db_session.commit()


def delete(*, db_session: Session, plan_id: int, user_id: int) -> bool:
    plan = get(db_session=db_session, plan_id=plan_id)
    if not plan or plan.user_id != user_id:
        raise NotFoundError("Workout plan not found")
    db_session.delete(plan)
    db_session.commit()
    return True


def save_generated_plan(
    *,
    db_session: Session,
    user_id: int,
    name: str,
    valid_from: date,
    valid_to: date,
    days_data: list[dict],
) -> WorkoutPlan:
    """Save a plan generated by the AI agent."""
    plan = WorkoutPlan(
        user_id=user_id,
        name=name,
        plan_type="generated",
        valid_from=valid_from,
        valid_to=valid_to,
    )
    db_session.add(plan)
    db_session.commit()
    db_session.refresh(plan)

    for day_data in days_data:
        day = WorkoutPlanDay(
            plan_id=plan.id,
            day_of_week=day_data["day_of_week"],
            focus=day_data["focus"],
            order_index=day_data.get("order_index", 0),
        )
        db_session.add(day)
        db_session.commit()
        db_session.refresh(day)

        for ex_data in day_data.get("exercises", []):
            exercise = WorkoutPlanExercise(
                plan_day_id=day.id,
                exercise_id=ex_data["exercise_id"],
                sets=ex_data.get("sets", 3),
                reps_min=ex_data.get("reps_min", 8),
                reps_max=ex_data.get("reps_max", 12),
                rest_seconds=ex_data.get("rest_seconds", 90),
                order_index=ex_data.get("order_index", 0),
                notes=ex_data.get("notes"),
            )
            db_session.add(exercise)

    db_session.commit()
    db_session.refresh(plan)
    return plan


def _to_plan_read(*, db_session: Session, plan: WorkoutPlan) -> WorkoutPlanRead:
    days_stmt = select(WorkoutPlanDay).where(WorkoutPlanDay.plan_id == plan.id).order_by(WorkoutPlanDay.order_index)
    days = db_session.exec(days_stmt).all()
    return WorkoutPlanRead(
        **plan.model_dump(),
        days=[_to_day_read(db_session=db_session, day=d) for d in days],
    )


def _to_day_read(*, db_session: Session, day: WorkoutPlanDay) -> WorkoutPlanDayRead:
    ex_stmt = (
        select(WorkoutPlanExercise)
        .where(WorkoutPlanExercise.plan_day_id == day.id)
        .order_by(WorkoutPlanExercise.order_index)
    )
    exercises = db_session.exec(ex_stmt).all()
    ex_reads = []
    for ex in exercises:
        exercise = db_session.get(Exercise, ex.exercise_id)
        ex_reads.append(WorkoutPlanExerciseRead(
            id=ex.id,
            exercise_id=ex.exercise_id,
            exercise_name=exercise.name if exercise else None,
            exercise_description=exercise.description if exercise else None,
            sets=ex.sets,
            reps_min=ex.reps_min,
            reps_max=ex.reps_max,
            rest_seconds=ex.rest_seconds,
            order_index=ex.order_index,
            notes=ex.notes,
        ))
    return WorkoutPlanDayRead(
        id=day.id,
        day_of_week=day.day_of_week,
        focus=day.focus,
        order_index=day.order_index,
        exercises=ex_reads,
    )
